/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-10 18:29:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/board/../lecture/inc/header.jsp", Long.valueOf(1610192951631L));
    _jspx_dependants.put("/WEB-INF/views/board/../lecture/inc/footer.jsp", Long.valueOf(1610196087716L));
    _jspx_dependants.put("/WEB-INF/views/board/../lecture/inc/nav.jsp", Long.valueOf(1610258998439L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<link href=\"/resources/css/board/semantic.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"/resources/css/board/coding-editor.css?v=PcJtV1wrr17HVXyCKnGcq8HaRlDqjrY-A38PRY6ClWY\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"/resources/css/board/common.css?v=yXd0S6u6SBGCn8osoY9ic1_wI_rAn4F1URWWZNbLafA\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"/resources/css/board/sub.css?v=HwHJcxMbM4H2DoH9sGsoRVXYsN_KPySvn4UexNJGjJ4\" rel=\"stylesheet\" />\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/animate.css\">\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#contain{\r\n");
      out.write("\tmargin: 5% 0 0 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">잡아오라</a>\r\n");
      out.write("     <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("       <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("   </button>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("       <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("         <li class=\"nav-item active\"><a href=\"index.html\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"about.html\" class=\"nav-link\">LoadMap</a></li>\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"course.html\" class=\"nav-link\">Course</a></li>\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"instructor.html\" class=\"nav-link\">Community</a></li>\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"blog.html\" class=\"nav-link\">FAQ</a></li>\r\n");
      out.write("         <li class=\"nav-item\">\r\n");
      out.write("         \t");
if(session.getAttribute("member")==null){//세션에 담겨진 데이터가 없다면 
      out.write("\r\n");
      out.write("\t         <a href=\"/loginForm\" class=\"nav-link\">Login</a>\r\n");
      out.write("\t        ");
} else { //세션에 담겨진 데이터가 있다면
      out.write("\r\n");
      out.write("\t         <a href=\"/loginout\" class=\"nav-link\">Logout</a>\r\n");
      out.write("\t        ");
} 
      out.write("\r\n");
      out.write("         </li>\r\n");
      out.write("     </ul>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- END nav -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- content -->\r\n");
      out.write("<div id=\"contain\">\r\n");
      out.write("    <div class=\"contain_in\">\r\n");
      out.write("        <div class=\"room_cover\">\r\n");
      out.write("            <div class=\"left_common\">\r\n");
      out.write("    <div class=\"top_info for_question\">\r\n");
      out.write("        <div id=\"question\"><p class=\"tit\">커뮤니티</p></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"mid_info\">\r\n");
      out.write("        <div class=\"drop_down\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"/Board/Notification/Public\" class=\"drop_btn\">공지사항</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"/Board/Community/Free/Info\" class=\"drop_btn\">소식 및 정보</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"/Board/Community/Free/Free\" class=\"drop_btn\">자유</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"/Board/Community/Free/Qna\" class=\"drop_btn\">질문 및 답변</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("            <div class=\"right_area\">\r\n");
      out.write("                <div class=\"board_wrap clear\">\r\n");
      out.write("                    <div class=\"Board\">\r\n");
      out.write("                        <div class=\"title clear\" style=\"float:left;\">\r\n");
      out.write("                            <h2 style=\"font-size:23px;\">&#xACF5;&#xC9C0;&#xC0AC;&#xD56D;</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ui selection dropdown opt\" style=\"float:right; margin-top:20px;\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"gender\">\r\n");
      out.write("                            <i class=\"dropdown icon\"></i>\r\n");
      out.write("                            <div class=\"text\">최신순</div>\r\n");
      out.write("                            <div class=\"menu\" id=\"orderSort\">\r\n");
      out.write("                                <div class=\"item active selected\" data-value=\"0\">최신순</div>\r\n");
      out.write("                                <div class=\"item\" data-value=\"1\">추천순</div>\r\n");
      out.write("                                <div class=\"item\" data-value=\"2\">댓글순</div>\r\n");
      out.write("                                <div class=\"item\" data-value=\"3\">조회순</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"boardTbl\">\r\n");
      out.write("                    <table class=\"ui padded table tbl001\">\r\n");
      out.write("                        <colgroup>\r\n");
      out.write("                            <col width=\"7%\" />\r\n");
      out.write("                            <col width=\"44%\" />\r\n");
      out.write("                            <col width=\"23%\" />\r\n");
      out.write("                            <col width=\"6%\" />\r\n");
      out.write("                            <col width=\"8%\" />\r\n");
      out.write("                            <col width=\"26%\" />\r\n");
      out.write("                        </colgroup>\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>번호</th>\r\n");
      out.write("                                <th>제목</th>\r\n");
      out.write("                                <th>작성자</th>\r\n");
      out.write("                                <th>추천</th>\r\n");
      out.write("                                <th>조회수</th>\r\n");
      out.write("                                <th>작성일</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>5</td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <a href=\"/Board/notification/public/service/41\">[&#xACF5;&#xD1B5;] 2018 &#xC774;&#xB370;&#xC77C;&#xB9AC; &#xCF54;&#xB529; &#xCC4C;&#xB9B0;&#xC9C0; &#xC131;&#xB8CC; </a>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td style=\"text-align:center\"><span class=\"person\"><img src=\"https://modustorage.blob.core.windows.net/image/de921afc-9b44-4e7f-9bc1-ffac04adced5___admin_profile.png\" alt=\"profileImg\"><a href=\"javascript:;\" class=\"nick\">&#xBAA8;&#xB450;&#xC758; &#xCF54;&#xB529;</a></span></td>\r\n");
      out.write("                                        <td>2</td>\r\n");
      out.write("                                        <td>309</td>\r\n");
      out.write("                                        <td>2018.11.05</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>4</td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <a href=\"/Board/notification/public/service/31\">&#xBAA8;&#xB450;&#xC758; &#xCF54;&#xB529; &#xC2DC;&#xD5D8; &#xBC0F; &#xACFC;&#xC81C;, &#xD3C9;&#xAC00; &#xAD00;&#xB9AC; &#xBCA0;&#xD0C0; &#xC11C;&#xBE44;&#xC2A4;  </a>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td style=\"text-align:center\"><span class=\"person\"><img src=\"/images/photoDefualt.png\" alt=\"profileImg\"><a href=\"javascript:;\" class=\"nick\">&#xAD00;&#xB9AC;&#xC790;</a></span></td>\r\n");
      out.write("                                        <td>0</td>\r\n");
      out.write("                                        <td>281</td>\r\n");
      out.write("                                        <td>2018.08.23</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>3</td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <a href=\"/Board/notification/public/service/27\">&#xC6D0;&#xD65C;&#xD55C; &#xBAA8;&#xB450;&#xC758; &#xCF54;&#xB529; &#xC774;&#xC6A9;&#xC744; &#xC704;&#xD55C; &#xC548;&#xB0B4;  </a>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td style=\"text-align:center\"><span class=\"person\"><img src=\"/images/photoDefualt.png\" alt=\"profileImg\"><a href=\"javascript:;\" class=\"nick\">&#xAD00;&#xB9AC;&#xC790;</a></span></td>\r\n");
      out.write("                                        <td>0</td>\r\n");
      out.write("                                        <td>153</td>\r\n");
      out.write("                                        <td>2018.07.31</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>2</td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <a href=\"/Board/notification/public/service/9\">&#xBAA8;&#xB450;&#xC758; &#xCF54;&#xB529; &#x2018;GS &#xC778;&#xC99D; 1&#xB4F1;&#xAE09; &#xD68D;&#xB4DD;&#x2019; </a>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td style=\"text-align:center\"><span class=\"person\"><img src=\"/images/photoDefualt.png\" alt=\"profileImg\"><a href=\"javascript:;\" class=\"nick\">&#xAD00;&#xB9AC;&#xC790;</a></span></td>\r\n");
      out.write("                                        <td>0</td>\r\n");
      out.write("                                        <td>142</td>\r\n");
      out.write("                                        <td>2018.07.18</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>1</td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <a href=\"/Board/notification/public/service/7\">&#xBAA8;&#xB450;&#xC758; &#xCF54;&#xB529; Version1.0 &#xC624;&#xD508; </a>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td style=\"text-align:center\"><span class=\"person\"><img src=\"/images/photoDefualt.png\" alt=\"profileImg\"><a href=\"javascript:;\" class=\"nick\">&#xAD00;&#xB9AC;&#xC790;</a></span></td>\r\n");
      out.write("                                        <td>0</td>\r\n");
      out.write("                                        <td>72</td>\r\n");
      out.write("                                        <td>2018.07.18</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"write\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"contentBottom\">\r\n");
      out.write("                    <div class=\"pagingNum clear\">\r\n");
      out.write("                        <div id=\"paging\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"ui selection dropdown opt upward\" style=\"padding-right:1em; padding-left:1.2em;\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"gender\">\r\n");
      out.write("                        <i class=\"caret up icon\" style=\"float:right\"></i>\r\n");
      out.write("                        <div class=\"text\">\r\n");
      out.write("제목                        </div>\r\n");
      out.write("                        <div id=\"searchType\" class=\"menu\">\r\n");
      out.write("                            <div class=\"item active selected\" data-value=\"2\">제목</div>\r\n");
      out.write("                            <div class=\"item \" data-value=\"3\">내용</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"ui icon input searchTextBox\">\r\n");
      out.write("                        <input id=\"searchTxt\" type=\"text\" placeholder=\"Search...\" value=\"\">\r\n");
      out.write("                        <i id=\"btnSearch\" class=\"search icon link\" onclick=\"fnBtnSearch_Click()\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //content -->\r\n");
      out.write("\r\n");
      out.write("<footer class=\"ftco-footer ftco-no-pt\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row mb-5\">\r\n");
      out.write("      <div class=\"col-md pt-5\">\r\n");
      out.write("        <div class=\"ftco-footer-widget pt-md-5 mb-4\">\r\n");
      out.write("          <h2 class=\"ftco-heading-2\">About</h2>\r\n");
      out.write("          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("          <ul class=\"ftco-footer-social list-unstyled float-md-left float-lft\">\r\n");
      out.write("            <li class=\"ftco-animate\"><a href=\"#\"><span class=\"fa fa-twitter\"></span></a></li>\r\n");
      out.write("            <li class=\"ftco-animate\"><a href=\"#\"><span class=\"fa fa-facebook\"></span></a></li>\r\n");
      out.write("            <li class=\"ftco-animate\"><a href=\"#\"><span class=\"fa fa-instagram\"></span></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md pt-5\">\r\n");
      out.write("    <div class=\"ftco-footer-widget pt-md-5 mb-4 ml-md-5\">\r\n");
      out.write("      <h2 class=\"ftco-heading-2\">Help Desk</h2>\r\n");
      out.write("      <ul class=\"list-unstyled\">\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Customer Care</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Legal Help</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Services</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Privacy and Policy</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Refund Policy</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Call Us</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md pt-5\">\r\n");
      out.write("   <div class=\"ftco-footer-widget pt-md-5 mb-4\">\r\n");
      out.write("      <h2 class=\"ftco-heading-2\">Recent Courses</h2>\r\n");
      out.write("      <ul class=\"list-unstyled\">\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Computer Engineering</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Web Design</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Business Studies</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Civil Engineering</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Computer Technician</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Web Developer</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md pt-5\">\r\n");
      out.write("    <div class=\"ftco-footer-widget pt-md-5 mb-4\">\r\n");
      out.write("       <h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("       <div class=\"block-23 mb-3\">\r\n");
      out.write("         <ul>\r\n");
      out.write("           <li><span class=\"icon fa fa-map-marker\"></span><span class=\"text\">203 Fake St. Mountain View, San Francisco, California, USA</span></li>\r\n");
      out.write("           <li><a href=\"#\"><span class=\"icon fa fa-phone\"></span><span class=\"text\">+2 392 3929 210</span></a></li>\r\n");
      out.write("           <li><a href=\"#\"><span class=\"icon fa fa-paper-plane\"></span><span class=\"text\">info@yourdomain.com</span></a></li>\r\n");
      out.write("       </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("    <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("      Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("      <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- loader -->\r\n");
      out.write("<div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/resources/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("<script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\r\n");
      out.write("<script src=\"/resources/js/google-map.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/main.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/member.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $(\".drop_box\").hide();\r\n");
      out.write("            var depth1 = $(\".sv_area\").data(\"depth1\");\r\n");
      out.write("            var depth2 = $(\".sv_area\").data(\"depth2\");\r\n");
      out.write("            var selectedUl;\r\n");
      out.write("            if (depth1 != null) {\r\n");
      out.write("                selectedUl = $(\"div.drop_box:eq(\" + depth1 + \")\");\r\n");
      out.write("                $(selectedUl).show();\r\n");
      out.write("            }\r\n");
      out.write("            if (depth2 != null) {\r\n");
      out.write("                $(selectedUl).find(\"li:eq(\" + depth2 + \")\").addClass(\"url_on\");\r\n");
      out.write("            }\r\n");
      out.write("            $(\".drop_btn\").click(function () {\r\n");
      out.write("                var drp = $(this).next(\"div.drop_box\");\r\n");
      out.write("                if ($(drp).is(\":visible\")) {\r\n");
      out.write("                    $(drp).slideUp();\r\n");
      out.write("                    $(this).children(\"span\").removeClass(\"active\");\r\n");
      out.write("                } else {\r\n");
      out.write("                    $(\".drop_box\").slideUp();\r\n");
      out.write("                    $(\".drop_btn span\").removeClass(\"active\");\r\n");
      out.write("                    $(drp).slideDown();\r\n");
      out.write("                    $(this).children(\"span\").addClass(\"active\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        var fnEnterEvent = function () {\r\n");
      out.write("            $(\".li_alarm\").mouseenter(function () {\r\n");
      out.write("                var message = $(this).data(\"content\");\r\n");
      out.write("                $(this).after(\"<textarea id='alarmContent' readonly style='width: 97%; height: 80px; padding: 10px; background-color: #fbfafa; overflow-y: hidden; resize: none; border-radius: 5px;'>\" + message + \"</textarea>\");\r\n");
      out.write("            });\r\n");
      out.write("            $(\".li_alarm\").mouseleave(function () {\r\n");
      out.write("                $(\"#alarmContent\").remove();\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function GetNotiList() {\r\n");
      out.write("            var obj = new Object();\r\n");
      out.write("            obj.OnBadge = true;\r\n");
      out.write("            obj.Read = false;\r\n");
      out.write("            obj.PageSize = 5;\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"/pushlog/list\",\r\n");
      out.write("                data: JSON.stringify(obj),\r\n");
      out.write("                timeout: 60 * 1000 * 30,\r\n");
      out.write("                contentType: 'application/json; charset=utf-8',\r\n");
      out.write("                error: function (response) {\r\n");
      out.write("                    console.log(response);\r\n");
      out.write("                    clearInterval(interval);\r\n");
      out.write("                },\r\n");
      out.write("                success: function (response) {\r\n");
      out.write("\r\n");
      out.write("                    if (response.totalCount > 0) {\r\n");
      out.write("                        $(\".alarm_icon .alarm_list .all\").css(\"display\", \"\");\r\n");
      out.write("                        $(\".alarm_icon .alarm_list .del\").css(\"display\", \"\");\r\n");
      out.write("                        $(\".alarm_icon .num\").css(\"display\", \"\");\r\n");
      out.write("                        $(\".alarm_icon .num\").html(response.totalCount);\r\n");
      out.write("                        $(\".alarm_list .list ul\").empty();\r\n");
      out.write("\r\n");
      out.write("                        $.each(response.result, function (i, noti) {\r\n");
      out.write("                            if (noti.message == \"|||sessionrefresh|||\" && $(\"#btnLabMove\").length == 0 && noti.pushData == 2) {\r\n");
      out.write("                                console.log(response.result);\r\n");
      out.write("                                $(\"#headerListButton .alarm_icon\").before(\"<li class='p_room' id='btnLabMove'><a href='/Channel/\" + noti.no + \"/'><img src='/images/lab_icon.png'/>코딩랩</a></li>\");\r\n");
      out.write("                            } else {\r\n");
      out.write("                                let li = $(\"<li />\").attr(\"id\", \"li_\" + noti.no).attr(\"class\", \"li_alarm\").attr(\"data-content\", noti.message).append($(\"<span />\").addClass(\"tit\").html(noti.message)).append('<a href=\"#\" class=\"notiReader\" data-value=\"' + noti.no + '\"><i class=\"icon close\"></i></a>');\r\n");
      out.write("                                $(\".alarm_list .list ul\").append(li);\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                        $(\"#headerListButton .alarm_list ul li\").click(function () {\r\n");
      out.write("                            window.location.href = '/MyCoding/My/Alarm';\r\n");
      out.write("                        });\r\n");
      out.write("\r\n");
      out.write("                        $(\".notiReader\").click(function () {\r\n");
      out.write("                            ReadNoti($(this).data(\"value\"));\r\n");
      out.write("                        });\r\n");
      out.write("\r\n");
      out.write("                        fnEnterEvent();\r\n");
      out.write("                    }\r\n");
      out.write("                    else {\r\n");
      out.write("                        NotiEmpty();\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function NotiEmpty() {\r\n");
      out.write("            $(\".alarm_icon .alarm_list .all\").css(\"display\", \"none\");\r\n");
      out.write("            $(\".alarm_icon .alarm_list .del\").css(\"display\", \"none\");\r\n");
      out.write("            $(\".alarm_icon .num\").css(\"display\", \"none\");\r\n");
      out.write("            $(\".alarm_list .list ul\").empty();\r\n");
      out.write("            $(\".alarm_list .list ul\").append(\"<li>알림이 없습니다.</li>\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 알림 읽음 처리\r\n");
      out.write("        function ReadNoti(no) {\r\n");
      out.write("            console.log(no);\r\n");
      out.write("            var obj = new Object();\r\n");
      out.write("            obj.PageNo = no;\r\n");
      out.write("            obj.PushLogNo = true;\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"/pushlog/setread\",\r\n");
      out.write("                data: JSON.stringify(obj),\r\n");
      out.write("                timeout: 60 * 1000 * 30,\r\n");
      out.write("                contentType: 'application/json; charset=utf-8',\r\n");
      out.write("                error: function (response) {\r\n");
      out.write("                    console.log(response);\r\n");
      out.write("                },\r\n");
      out.write("                success: function (response) {\r\n");
      out.write("                    $(\"#alarmContent\").remove();\r\n");
      out.write("                    if (response.result > 0) {\r\n");
      out.write("                        $(\"#li_\" + no).remove();\r\n");
      out.write("                        if ($(\"#top_bar .alarm_list .list ul li\").length < 1) NotiEmpty();\r\n");
      out.write("                    }\r\n");
      out.write("                    else {\r\n");
      out.write("                        console.log(response);\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 모든 알림 읽음 처리\r\n");
      out.write("        function ReadAllNoti() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"/pushlog/setreadall/\",\r\n");
      out.write("                timeout: 60 * 1000 * 30,\r\n");
      out.write("                contentType: 'application/json; charset=utf-8',\r\n");
      out.write("                error: function (response) {\r\n");
      out.write("                    console.log(response);\r\n");
      out.write("                },\r\n");
      out.write("                success: function (response) {\r\n");
      out.write("                    NotiEmpty();\r\n");
      out.write("                    $(\".alarm_list\").css(\"display\", \"none\");\r\n");
      out.write("                    $(\"#alarmContent\").remove();\r\n");
      out.write("                    AlertModal(\"모든 알림을 읽었습니다.\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 모든 알림 삭제 처리\r\n");
      out.write("        function DeleteAllNoti() {\r\n");
      out.write("            if (confirm(\"모든 알림이 삭제됩니다. 삭제하시겠습니까?\")) {\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    type: \"post\",\r\n");
      out.write("                    url: \"/pushlog/removeall\",\r\n");
      out.write("                    timeout: 60 * 1000 * 30,\r\n");
      out.write("                    contentType: 'application/json; charset=utf-8',\r\n");
      out.write("                    error: function (response) {\r\n");
      out.write("                        console.log(response);\r\n");
      out.write("                    },\r\n");
      out.write("                    success: function (response) {\r\n");
      out.write("                        NotiEmpty();\r\n");
      out.write("                        $(\".alarm_list\").css(\"display\", \"none\");\r\n");
      out.write("                        AlertModal(\"모든 알림을 삭제했습니다.\");\r\n");
      out.write("                        $(\"#alarmContent\").remove();\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var AlertModal = function (text, type, time) {\r\n");
      out.write("            let modal = document.getElementsByClassName(\"effect\")[0];\r\n");
      out.write("            document.getElementsByClassName(\"effect\")[0].querySelector(\"#saveModalText\").innerHTML = text;\r\n");
      out.write("            modal.setAttribute(\"style\", \"right: 0;\");\r\n");
      out.write("            modal.style.right = \"0\";\r\n");
      out.write("            if (type == \"error\" || type == \"Error\" || type == \"false\" || type == false || type == \"red\") {\r\n");
      out.write("                modal.style.background = \"#dd1111\";\r\n");
      out.write("            } else {\r\n");
      out.write("                modal.style.background = \"rgb(46, 174, 248, 1)\";\r\n");
      out.write("            }\r\n");
      out.write("            if (time != null) setTimeout(function () { modal.style.right = \"-600px\"; }, time);\r\n");
      out.write("            else setTimeout(function () { modal.style.right = \"-600px\"; }, 1500);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        window.onbeforeunload = function () {\r\n");
      out.write("            clearInterval(interval);\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"/lib/jquery.paging.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $(function () {\r\n");
      out.write("            var maxPage = '5';\r\n");
      out.write("\r\n");
      out.write("            maxPage = Math.ceil(Number(maxPage / 10));\r\n");
      out.write("\r\n");
      out.write("            if (maxPage < 2) {\r\n");
      out.write("                $(\"#paging\").hide();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (5 > 0) {\r\n");
      out.write("                $(\"#paging\").paging({\r\n");
      out.write("                    current: 1, max: maxPage,\r\n");
      out.write("                    onclick(e, pageNo) {\r\n");
      out.write("                        fnBtnSearch_Click(pageNo);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            $(\"#btnSearch\").on(\"click\", fnBtnSearch_Click);\r\n");
      out.write("\r\n");
      out.write("            $(\"#searchTxt\").keyup(function (e)\r\n");
      out.write("            {\r\n");
      out.write("               if (e.keyCode == 13) fnBtnSearch_Click();\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            //shearch box upward\r\n");
      out.write("            $(\".ui.selection.dropdown.opt.upward\").dropdown({\r\n");
      out.write("                direction: 'upward'\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        var fnBtnSearch_Click = function (pageNo)\r\n");
      out.write("        {\r\n");
      out.write("            var searchType = $(\"#searchType div.selected\").data('value');\r\n");
      out.write("            var searchTxt = $(\"#searchTxt\").val();\r\n");
      out.write("            var url = \"notification/public/service?pageNo=\" + pageNo + \"&searchType=\" + searchType + \"&searchTxt=\" + searchTxt\r\n");
      out.write("            location.href = \"/Board/\" + url\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
