/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-16 19:22:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jscompany.springproject.model.domain.lecture.Lecture;
import java.util.List;
import com.jscompany.springproject.model.domain.member.Member;

public final class mycourselist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/member/../lecture/inc/nav.jsp", Long.valueOf(1610823506910L));
    _jspx_dependants.put("/WEB-INF/views/member/../lecture/inc/footer.jsp", Long.valueOf(1610789367084L));
    _jspx_dependants.put("/WEB-INF/views/member/../lecture/inc/header.jsp", Long.valueOf(1610680807101L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.jscompany.springproject.model.domain.lecture.Lecture");
    _jspx_imports_classes.add("com.jscompany.springproject.model.domain.member.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

	List<Lecture> lectureList = (List)request.getAttribute("lectureList"); 

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <title>CoCo!</title>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/animate.css\">\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/lecture/course.css\">\n");
      out.write("    <script src=\"/resources/js/lecture/course.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\r\n");
      out.write("\r\n");

	Member member = (Member)session.getAttribute("member");

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">잡아오라</a>\r\n");
      out.write("     <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("       <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("   </button>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("       <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"/\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"/course/list?topcategory_id=1\" class=\"nav-link\">Course</a></li>\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"/board/notice\" class=\"nav-link\">Community</a></li>\r\n");
      out.write("         <li class=\"nav-item\">\r\n");
      out.write("         \t");
if(session.getAttribute("member")==null){//세션에 담겨진 데이터가 없다면 
      out.write("\r\n");
      out.write("\t         <a href=\"/loginForm\" class=\"nav-link\">Login</a>\r\n");
      out.write("\t        ");
} else { //세션에 담겨진 데이터가 있다면
      out.write("\r\n");
      out.write("\t         <a href=\"/loginout\" class=\"nav-link\">Logout</a>\r\n");
      out.write("\t        ");
} 
      out.write("\r\n");
      out.write("         </li>\r\n");
      out.write("         ");
if(session.getAttribute("member")!=null){//세션에 담겨진 데이터가 없다면 
      out.write("\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"/mycourselist?member_id=");
      out.print(member.getMember_id() );
      out.write("\" class=\"nav-link\">DashBoard</a></li>\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"/mypage?mypage=1\" class=\"nav-link\">MyPage</a></li>\r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("         ");
if(session.getAttribute("member")!=null){
      out.write("\r\n");
      out.write("        \t ");
if(member.getAdmin_state() == 1) {
      out.write("\r\n");
      out.write("         \t\t<li class=\"nav-item\"><a href=\"/admin/list\" class=\"nav-link\">AdminPage</a></li>\r\n");
      out.write("         \t");
} 
      out.write("\r\n");
      out.write("         \t ");
if(member.getTeacher_state_id() == 1) {
      out.write("\r\n");
      out.write("         \t\t<li class=\"nav-item\"><a href=\"/lecture/list\" class=\"nav-link\">TeacherPage</a></li>\r\n");
      out.write("         \t");
} 
      out.write("\r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("     </ul>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- END nav -->");
      out.write("\n");
      out.write("<!-- END nav -->\n");
      out.write("\t");
if(session.getAttribute("member")==null) {
      out.write("\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\tlocation.href = \"/\";\n");
      out.write("\t\t</script>\n");
      out.write("\t");
} 
      out.write("\n");
      out.write("\t\n");
      out.write("\t<section class=\"ftco-section bg-light\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-9\">\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"width:1200px;\">\n");
      out.write("\t\t\t\t\t\t");
for(int i = 0; i < lectureList.size(); i++){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t");
Lecture lecture = lectureList.get(i); 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6 d-flex align-items-stretch ftco-animate\" style=\"width:20px;\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"project-wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/lectureview?lecture_id=");
      out.print(lecture.getLecture_id() );
      out.write("\" class=\"img\" style=\"background-image: url(/resources/data/logo/");
      out.print(lecture.getLecture_id());
      out.write('.');
      out.print(lecture.getLogofile());
      out.write(");\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"text p-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"/lectureview?lecture_id=");
      out.print(lecture.getLecture_id() );
      out.write('"');
      out.write('>');
      out.print(lecture.getLecture_name() );
      out.write("</a></h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"row mt-5\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"block-27\">\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">&lt;</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"active\"><span>1</span></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">2</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">3</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">4</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">5</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">&gt;</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</section>\n");
      out.write("\r\n");
      out.write("<footer class=\"ftco-footer ftco-no-pt\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row mb-5\">\r\n");
      out.write("      <div class=\"col-md pt-5\">\r\n");
      out.write("        <div class=\"ftco-footer-widget pt-md-5 mb-4\">\r\n");
      out.write("          <h2 class=\"ftco-heading-2\">잡아오라</h2>\r\n");
      out.write("          <p>코드를 익히는건 산을 오를는것과 같습니다. 조금씩 조금씩 다른 강사분들의 강의를 습득하고 이해하다 보면 자연스래 정상에 위치에 있을겁니다!</p>\r\n");
      out.write("          <ul class=\"ftco-footer-social list-unstyled float-md-left float-lft\">\r\n");
      out.write("            <li class=\"ftco-animate\"><a href=\"#\"><span class=\"fa fa-twitter\"></span></a></li>\r\n");
      out.write("            <li class=\"ftco-animate\"><a href=\"#\"><span class=\"fa fa-facebook\"></span></a></li>\r\n");
      out.write("            <li class=\"ftco-animate\"><a href=\"#\"><span class=\"fa fa-instagram\"></span></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md pt-5\">\r\n");
      out.write("    <div class=\"ftco-footer-widget pt-md-5 mb-4 ml-md-5\">\r\n");
      out.write("      <h2 class=\"ftco-heading-2\">고객센터</h2>\r\n");
      out.write("      <ul class=\"list-unstyled\">\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Qna</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">이용 약관</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">개인정보취급방침</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md pt-5\">\r\n");
      out.write("   <div class=\"ftco-footer-widget pt-md-5 mb-4\">\r\n");
      out.write("      <h2 class=\"ftco-heading-2\">커뮤니티</h2>\r\n");
      out.write("      <ul class=\"list-unstyled\">\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">공지사항</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">자유 게시판</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">질문과 답변</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md pt-5\">\r\n");
      out.write("    <div class=\"ftco-footer-widget pt-md-5 mb-4\">\r\n");
      out.write("       <h2 class=\"ftco-heading-2\">JS Company</h2>\r\n");
      out.write("       <div class=\"block-23 mb-3\">\r\n");
      out.write("         <ul>\r\n");
      out.write("           <li><span class=\"icon fa fa-map-marker\"></span><span class=\"text\">서울 구로구 어딘가에 위치한 저택의 한공간</span></li>\r\n");
      out.write("           <li><a href=\"#\"><span class=\"icon fa fa-phone\"></span><span class=\"text\">010 2940 8805</span></a></li>\r\n");
      out.write("           <li><a href=\"#\"><span class=\"icon fa fa-paper-plane\"></span><span class=\"text\">kjsj20@naver.com</span></a></li>\r\n");
      out.write("       </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("    <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("      (주)JSpompany &copy;<script>document.write(new Date().getFullYear());</script> 대표자 : 김재성 | 사업자번호 : 000-00-00000\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- loader -->\r\n");
      out.write("<div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/resources/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/main.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/member.js\"></script>\r\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("$(function(){\n");
      out.write("\t$('#topCategory'+$('#topcategory_id').val()).addClass('active');\n");
      out.write("\t$('#subCategory'+$('#subcategory_id').val()).addClass('active');\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
