/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-16 18:58:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.lecture.course;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jscompany.springproject.model.domain.lecture.Section_detail;
import com.jscompany.springproject.model.domain.lecture.Section;
import java.util.List;
import com.jscompany.springproject.common.Formatter;
import com.jscompany.springproject.model.domain.lecture.Lecture;
import com.jscompany.springproject.model.domain.member.Member;

public final class course_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/lecture/course/../inc/nav.jsp", Long.valueOf(1610823506910L));
    _jspx_dependants.put("/WEB-INF/views/lecture/course/../inc/footer.jsp", Long.valueOf(1610789367084L));
    _jspx_dependants.put("/WEB-INF/views/lecture/course/../inc/header.jsp", Long.valueOf(1610680807101L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.jscompany.springproject.model.domain.lecture.Section_detail");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.jscompany.springproject.common.Formatter");
    _jspx_imports_classes.add("com.jscompany.springproject.model.domain.lecture.Lecture");
    _jspx_imports_classes.add("com.jscompany.springproject.model.domain.lecture.Section");
    _jspx_imports_classes.add("com.jscompany.springproject.model.domain.member.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	Lecture lecture = (Lecture)request.getAttribute("lecture");
	List<Section> sectionList = (List)request.getAttribute("sectionList");
	List<List<Section_detail>> sectionDetailListList = (List)request.getAttribute("sectionDetailListList");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <title>CoCo!</title>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/lecture/course.css\">\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/animate.css\">\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>");
      out.write("\n");
      out.write("    <script src=\"/resources/js/lecture/course.js\"></script>\n");
      out.write("    <style>\n");
      out.write("    .class_info .left_thumbnail {\n");
      out.write("     \tfloat: left; \n");
      out.write("     \twidth: 270px; \n");
      out.write("    \tmargin-right: 30px; \n");
      out.write("    \tbox-sizing: border-box;\n");
      out.write("\t}\n");
      out.write("\t.class_info .right_information {\n");
      out.write("    \twidth: calc(100% - 300px);\n");
      out.write("    \tfloat: left;\n");
      out.write("\t}\n");
      out.write("    </style>\n");
      out.write("    <script type=\"text/javascript\" src=\"https://service.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body style=\"\">\n");
      out.write("\r\n");
      out.write("\r\n");

	Member member = (Member)session.getAttribute("member");

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">잡아오라</a>\r\n");
      out.write("     <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("       <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("   </button>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("       <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"/\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"/course/list?topcategory_id=1\" class=\"nav-link\">Course</a></li>\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"/board/notice\" class=\"nav-link\">Community</a></li>\r\n");
      out.write("         <li class=\"nav-item\">\r\n");
      out.write("         \t");
if(session.getAttribute("member")==null){//세션에 담겨진 데이터가 없다면 
      out.write("\r\n");
      out.write("\t         <a href=\"/loginForm\" class=\"nav-link\">Login</a>\r\n");
      out.write("\t        ");
} else { //세션에 담겨진 데이터가 있다면
      out.write("\r\n");
      out.write("\t         <a href=\"/loginout\" class=\"nav-link\">Logout</a>\r\n");
      out.write("\t        ");
} 
      out.write("\r\n");
      out.write("         </li>\r\n");
      out.write("         ");
if(session.getAttribute("member")!=null){//세션에 담겨진 데이터가 없다면 
      out.write("\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"/mycourselist?member_id=");
      out.print(member.getMember_id() );
      out.write("\" class=\"nav-link\">DashBoard</a></li>\r\n");
      out.write("         <li class=\"nav-item\"><a href=\"/mypage?mypage=1\" class=\"nav-link\">MyPage</a></li>\r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("         ");
if(session.getAttribute("member")!=null){
      out.write("\r\n");
      out.write("        \t ");
if(member.getAdmin_state() == 1) {
      out.write("\r\n");
      out.write("         \t\t<li class=\"nav-item\"><a href=\"/admin/list\" class=\"nav-link\">AdminPage</a></li>\r\n");
      out.write("         \t");
} 
      out.write("\r\n");
      out.write("         \t ");
if(member.getTeacher_state_id() == 1) {
      out.write("\r\n");
      out.write("         \t\t<li class=\"nav-item\"><a href=\"/lecture/list\" class=\"nav-link\">TeacherPage</a></li>\r\n");
      out.write("         \t");
} 
      out.write("\r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("     </ul>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!-- END nav -->");
      out.write('\n');
      out.write('	');
if(session.getAttribute("member") != null){ 
      out.write("\n");
      out.write("\t\t<input id=\"member_id\" type=\"hidden\" value=\"");
      out.print(member.getMember_id());
      out.write("\">\n");
      out.write("\t\t<input id=\"user_name\" type=\"hidden\" value=\"");
      out.print(member.getUser_name());
      out.write("\">\n");
      out.write("\t\t<input id=\"e_mail\" type=\"hidden\" value=\"");
      out.print(member.getE_mail());
      out.write("\">\n");
      out.write("\t\t<input id=\"phone\" type=\"hidden\" value=\"");
      out.print(member.getPhone());
      out.write("\">\n");
      out.write("\t");
} 
      out.write("\n");
      out.write("\t<input id=\"lecture_id\" type=\"hidden\" value=\"");
      out.print(lecture.getLecture_id());
      out.write("\">\n");
      out.write("\t<input id=\"price\" type=\"hidden\" value=\"");
      out.print(lecture.getPrice());
      out.write("\">\n");
      out.write("\t<section class=\"ftco-section bg-light\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-9\" style=\"color: black;\">\n");
      out.write("\t\t\t\t\t<div class=\"class_info\">\n");
      out.write("\t                    <div class=\"left_thumbnail\">\n");
      out.write("\t                        <span>\n");
      out.write("\t                            <img src=\"/resources/data/logo/");
      out.print(lecture.getLecture_id());
      out.write('.');
      out.print(lecture.getLogofile());
      out.write("\" alt=\"courseImg\" style=\"width:270px; height: 218px; border : 1px solid #D8D8D8; border-radius: 10px;\" />\n");
      out.write("\t                        </span>\n");
      out.write("\t                    </div>\n");
      out.write("\t                    <div class=\"right_information\" style=\"margin-bottom:40px;\">\n");
      out.write("\t                        <div class=\"top\">\n");
      out.write("\t                            <p class=\"tit\" style=\"font-weight:bold;\"><h3>");
      out.print(lecture.getLecture_name() );
      out.write("</h3></p>\n");
      out.write("\t                        </div>\n");
      out.write("\t                        <div class=\"mid\">\n");
      out.write("\t                            <span class=\"class_type\" style = \"background-color:#2E9AFE; color: #ffffff; padding: 5px; border-radius: 6px;\">");
      out.print(lecture.getLecture_subcategory_name() );
      out.write("</span>\n");
      out.write("\t                            &nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("\t                            ");
if(session.getAttribute("member") != null){ 
      out.write("\n");
      out.write("\t                            <input id=\"courseRegist\" type = \"button\" value=\"✔수강신청\" style=\"border-radius: 5px; padding: 3px; border : none;color: #ffffff; background-color:#0000FF;\"/>\n");
      out.write("\t                            ");
} else{ 
      out.write("\n");
      out.write("\t                            <input id=\"registIdNull\" type = \"button\" value=\"✔수강신청\" style=\"border-radius: 5px; padding: 3px; border : none;color: #ffffff; background-color:#0000FF;\"/>\n");
      out.write("\t                            ");
} 
      out.write("\n");
      out.write("\t                            <br/>\n");
      out.write("\t                            <br/>\n");
      out.write("\t                            <span>\n");
      out.write("\t                            \t<h4>가격 : \n");
      out.write("\t                            \t");
if(lecture.getPrice()==0){ 
      out.write("\n");
      out.write("\t                            \t\t무료\n");
      out.write("\t                            \t");
} else {
      out.write("\n");
      out.write("\t                            \t\t");
      out.print(Formatter.getCurrency(lecture.getPrice()));
      out.write("\n");
      out.write("\t                            \t");
} 
      out.write("\n");
      out.write("\t                            \t</h4>\n");
      out.write("\t                            </span>\n");
      out.write("\t                            <span><h4>강사 : ");
      out.print(lecture.getUser_name());
      out.write("</h4></span>\n");
      out.write("\t                        </div>\n");
      out.write("\t                    </div>\n");
      out.write("\t                </div>\n");
      out.write("\t\t\t\t\t<div class=\"summaryContent\" style=\"width : 100%; float : left; border : 1px solid #D8D8D8; border-radius: 6px; padding:20px; margin-bottom:40px;\">\n");
      out.write("\t\t\t\t\t\t<h4>강의 요약</h4>\n");
      out.write("\t\t\t\t\t\t<hr/>\n");
      out.write("\t\t\t\t\t\t");
      out.print(lecture.getLecture_summary_content() );
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<br/>\n");
      out.write("\t\t\t\t\t<div class=\"detailContent\" style=\"width : 100%; float : left; border : 1px solid #D8D8D8; border-radius: 6px; padding:20px;\">\n");
      out.write("\t\t\t\t\t\t<h3>✔강의 소개</h3>\n");
      out.write("\t\t\t\t\t\t<hr/>\n");
      out.write("\t\t\t\t\t\t");
      out.print(lecture.getLecture_detail_content() );
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class =\"sectionCategory\">\n");
      out.write("\t\t\t\t\t");
for(int i = 0; i < sectionList.size(); i++) {
      out.write("\n");
      out.write("\t\t\t\t\t");
Section section = sectionList.get(i); 
      out.write("\n");
      out.write("\t\t\t\t    \t<div id = \"section");
      out.print(section.getSection_id() );
      out.write("\" class=\"label\" style=\"cursor: pointer;\"><p><h5 style=\"font-weight:bold;\">");
      out.print(section.getSection_name() );
      out.write("</h5></p></div>\n");
      out.write("\t\t\t\t    \t");
List<Section_detail> sectionDetailList = sectionDetailListList.get(i); 
      out.write("\n");
      out.write("\t\t\t\t    \t\t<div id = \"section_detail");
      out.print(section.getSection_id() );
      out.write("\" class=\"elements\" style=\"font-weight:bold;\">\n");
      out.write("\t\t\t\t    \t\t");
for(int j = 0; j < sectionDetailList.size(); j++){ 
      out.write("\n");
      out.write("\t\t\t\t    \t\t\t");
Section_detail section_detail = sectionDetailList.get(j); 
      out.write("\n");
      out.write("\t\t\t\t    \t\t\t<p>");
      out.print(section_detail.getSection_detail_name() );
      out.write("</p>\n");
      out.write("\t\t\t\t    \t\t\t");
if(j != sectionDetailList.size()-1){ 
      out.write("\n");
      out.write("\t\t\t\t    \t\t\t\t<hr>\n");
      out.write("\t\t\t\t    \t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t    \t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t    \t\t</div>\n");
      out.write("\t\t\t\t    ");
} 
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\r\n");
      out.write("<footer class=\"ftco-footer ftco-no-pt\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row mb-5\">\r\n");
      out.write("      <div class=\"col-md pt-5\">\r\n");
      out.write("        <div class=\"ftco-footer-widget pt-md-5 mb-4\">\r\n");
      out.write("          <h2 class=\"ftco-heading-2\">잡아오라</h2>\r\n");
      out.write("          <p>코드를 익히는건 산을 오를는것과 같습니다. 조금씩 조금씩 다른 강사분들의 강의를 습득하고 이해하다 보면 자연스래 정상에 위치에 있을겁니다!</p>\r\n");
      out.write("          <ul class=\"ftco-footer-social list-unstyled float-md-left float-lft\">\r\n");
      out.write("            <li class=\"ftco-animate\"><a href=\"#\"><span class=\"fa fa-twitter\"></span></a></li>\r\n");
      out.write("            <li class=\"ftco-animate\"><a href=\"#\"><span class=\"fa fa-facebook\"></span></a></li>\r\n");
      out.write("            <li class=\"ftco-animate\"><a href=\"#\"><span class=\"fa fa-instagram\"></span></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md pt-5\">\r\n");
      out.write("    <div class=\"ftco-footer-widget pt-md-5 mb-4 ml-md-5\">\r\n");
      out.write("      <h2 class=\"ftco-heading-2\">고객센터</h2>\r\n");
      out.write("      <ul class=\"list-unstyled\">\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">Qna</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">이용 약관</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">개인정보취급방침</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md pt-5\">\r\n");
      out.write("   <div class=\"ftco-footer-widget pt-md-5 mb-4\">\r\n");
      out.write("      <h2 class=\"ftco-heading-2\">커뮤니티</h2>\r\n");
      out.write("      <ul class=\"list-unstyled\">\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">공지사항</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">자유 게시판</a></li>\r\n");
      out.write("        <li><a href=\"#\" class=\"py-2 d-block\">질문과 답변</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md pt-5\">\r\n");
      out.write("    <div class=\"ftco-footer-widget pt-md-5 mb-4\">\r\n");
      out.write("       <h2 class=\"ftco-heading-2\">JS Company</h2>\r\n");
      out.write("       <div class=\"block-23 mb-3\">\r\n");
      out.write("         <ul>\r\n");
      out.write("           <li><span class=\"icon fa fa-map-marker\"></span><span class=\"text\">서울 구로구 어딘가에 위치한 저택의 한공간</span></li>\r\n");
      out.write("           <li><a href=\"#\"><span class=\"icon fa fa-phone\"></span><span class=\"text\">010 2940 8805</span></a></li>\r\n");
      out.write("           <li><a href=\"#\"><span class=\"icon fa fa-paper-plane\"></span><span class=\"text\">kjsj20@naver.com</span></a></li>\r\n");
      out.write("       </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("    <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("      (주)JSpompany &copy;<script>document.write(new Date().getFullYear());</script> 대표자 : 김재성 | 사업자번호 : 000-00-00000\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- loader -->\r\n");
      out.write("<div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/resources/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/main.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/member.js\"></script>\r\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
